/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'GD32H759I_START' 
 * Target:  'GD32H759_NN_Invoke' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "gd32h7xx.h"



#endif /* RTE_COMPONENTS_H */
